### ISSUE TITLE
Attempting to create a subscription without OwnerId/User Id results in exception

### ISSUE THREAD

**Issue by andrewdmoreno** [mirsaeedi/dotnet-apim#13]
**Template:**
````
subscriptions:
  - name: MySubscription
    displayName: "Subscription for My Api"
    scope: /apis/my-api
````

**Expected Result:**
Creates arm

**Actual Result**
`SubscriptionDeploymentDefinition.DependentUser()` throws `ArgumentNullException`
