### ISSUE TITLE
Api Policy xml used when creating operation policies

### ISSUE THREAD

**Issue by andrewdmoreno** [mirsaeedi/dotnet-apim#14]
Unable to create operation policies successfully. Consider the following:

**Template**
````
apis:
    ....
    policy: .\api-policy.xml
    operations:
      operation1:
        policy: .\operation1-policy.xml
````

**Expected Result**
Policy from `operation1-policy.xml` is used when creating the arm for the operation1 policy

**Actual Result**
The policy from `api-policy.xml` is used to create the operation1 policy.
