### ISSUE TITLE
Description of the API is not updated when deploying to APIM

### ISSUE THREAD

**Issue by iabhee** [mirsaeedi/dotnet-apim#29]
```
version: 0.0.1
apimServiceName: myAPIMService

apis:
    - name: myApi
      type: http
      _**description: myFirstApi**.  --> (not updated when deployed to APIM)_
      serviceUrl: http://myApiBackendUrl.com
```

noticed in the generated ARM template the way it constructs the "value" under resources it doesn't include the "Description" when passing the whole open API spec and when i manually added the "Description" it worked. 

Could you please add this property so that the tool automatically adds it when the ARM template is generated? 

```
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "ApimServiceName": {
      "type": "string",
      "metadata": {
        "description": "Name of the API Management"
      }
    }
  },
  "variables": {},
  "resources": [
    {
      "properties": {
        "value": "{ }", ---> this doesn't have the description property set
        "format": "openapi+json",
        "Description": "myFirstApi",
        "type": "http",
        "apiRevision": "1",
        "isCurrent": true,
        "subscriptionRequired": false,
        "displayName": "myFirstAPI",
        "serviceUrl": "https://myapp-webapp.azurewebsites.net",
        "path": "find"
      },

```
