### ISSUE TITLE
How do you link Application Insights to an API

### ISSUE THREAD

**Issue by clouddna-au** [mirsaeedi/dotnet-apim#42]
Hi

Thanks for the tool. 

How do you link the logger for application insights to an api like the yaml provides from MS https://github.com/Azure/azure-api-management-devops-resource-kit/blob/main/src/README.md#APIDiagnosticConfiguration

If I try and add it, I receive an exception 

`2022-07-05T01:43:42.4477879Z System.AggregateException: One or more errors occurred. ((Line: 6, Col: 5, Idx: 164) - (Line: 6, Col: 5, Idx: 164): Exception during deserialization)
2022-07-05T01:43:42.4480896Z  ---> YamlDotNet.Core.YamlException: (Line: 6, Col: 5, Idx: 164) - (Line: 6, Col: 5, Idx: 164): Exception during deserialization
2022-07-05T01:43:42.4514802Z  ---> System.Runtime.Serialization.SerializationException: Property 'diagnostic' not found on type 'Apim.DevOps.Toolkit.Core.DeploymentDefinitions.Entities.ApiDeploymentDefinition'.
2022-07-05T01:43:42.4520876Z    at YamlDotNet.Serialization.TypeInspectors.TypeInspectorSkeleton.GetProperty(Type type, Object container, String name, Boolean ignoreUnmatched)
2022-07-05T01:43:42.4526489Z    at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
2022-07-05T01:43:42.4528339Z   `

**Comment by mirsaeedi** [comment]
Hello buddy. The diagnostics are not supported at this point. They will be included in the next release. June 8th.

**Comment by clouddna-au** [comment]
Cheers mate, is there perhaps a list of items that will be inbcluded in new release, thanks a lot for the release and app. Is it July 8th as you mentioned June 8th?

**Comment by mirsaeedi** [comment]
Hey, you can get the latest [package](https://www.nuget.org/packages/Apim.DevOps.Toolkit/2.0.3). And, here's a [sample](https://github.com/mirsaeedi/dotnet-apim/blob/master/src/Examples/Definitions/API_Logger_Diagnostics.yml) on how to add application insights:

1. Create a new Application Insights in Azure
2. Create a new Logger in your APIM, either via the yml file or manually.
3. Reference the logger in the API section.

```yml
version: 0.0.1 # Required
apimServiceName: $(apimServiceName) # Required, must match name of an apim service deployed in the specified resource group

# Specify global policy (Optional)
policy: $(apimBasePath)\Policies\GlobalPolicy.xml

apis:
  - name: ApiE1
    displayName: API E v1
    serviceUrl: $(ApiServiceURL)
    openApiSpec: $(apimBasePath)\OpenApi.json
    policy: $(apimBasePath)\Policies\ApiPolicy.xml
    path: $(prefix)/e/api
    protocols: https
    subscriptionRequired: true
    isCurrent: true
    subscriptionKeyParameterNames:
      header: ProviderKey
      query: ProviderKey
    diagnostics:
      alwaysLog: allErrors
      loggerId: myAppInsights2 # The id of the logger.
      sampling:
        samplingType: fixed
        percentage: 50
      frontend: 
        request:
          headers:
          body: 
            bytes: 512
        response: 
          headers:
          body: 
            bytes: 512
      backend: 
        request:
          headers:
          body: 
            bytes: 512
        response: 
          headers:
          body: 
            bytes: 512
      enableHttpCorrelationHeaders: true

loggers:
    - name: myAppInsights2
      resourceId: $(appInsightName) #The name of the Azure Application Insights resource.
      loggerType: applicationInsights
      description: a test app insights
      credentials:
        instrumentationKey: $(instrumentationKey) #The instrumentation key of the Azure Application Insights resource.
      isBuffered: true
```

Note that variables in `$(variable_name)` are passed to the tool. Look at Readme for more info about variables.
