### ISSUE TITLE
Tag not found exception when adding a tag that does not exist on APIM

### ISSUE THREAD

**Issue by Meertman** [mirsaeedi/dotnet-apim#59]
When using the dotnet-apim tool for generating the ARM templates for creating your API in APIM, the tool allows you to specify tags. 

However, our ARM template deployment fails with the message: 'Tag not found. (Code: ResourceNotFound)'

It seems that the tag needs to exist on the APIM instance first in order for the deployment of the ARM template to work, as mentioned in this GIT hub issue as well: https://github.com/MicrosoftDocs/azure-docs/issues/21817

Currently we work around this issue by having an azure CLI command for creating the tags, but could the code also generate an ARM template for the creation of the tags on the APIM instance, e.g.

```
{
    "type": "Microsoft.ApiManagement/service/tags",
    "apiVersion": "2022-09-01-preview",
    "name": "[concat(parameters('service_apim_name'), parameters('tag_name')]",
    "dependsOn": [
        "[resourceId('Microsoft.ApiManagement/service', parameters('service_apim_name'))]"
    ],
    "properties": {
        "displayName": "parameters('tag_name')"
    }
}
```

**Comment by Meertman** [comment]
Okay, my bad, just figured out that you also need to specify the tags separately in order for them to be created by the tool, like so:

```
apis:
  - name: <some-name>
    ...
    tags: "<tag-1>,<tag-2>,<tag-3>"
    ...

tags:
  - name: <tag-1>
    displayName: <tag-1>
  - name: <tag-2>
    displayName: <tag-2>
  - name: <tag-3>
    displayName: <tag-3>
```
    
So closing the issue as it is not relevant anymore.
